public_gsheets_url = "https://docs.google.com/spreadsheets/d/1wSmbtEbAj7SLLVo51ts3GLuh_LHyKb2pINCCVxblm6o/edit?usp=sharing"
public_sheet_csv = "https://docs.google.com/spreadsheets/d/1wSmbtEbAj7SLLVo51ts3GLuh_LHyKb2pINCCVxblm6o/export?format=csv&gid=288635424"
kariyer_sifre = ""